version: '3'

services:
  production:
    build:
      context: .
      dockerfile: production.dockerfile
    image: istudyatuni/sea-battle:latest
    ports:
      - 80:80

  sea-battle:
    image: istudyatuni/sea-battle:latest
    ports:
      - 80:80
